### ISSUE TITLE
cartella OsmAndMapCreator-main

### ISSUE THREAD

**Issue by cascafico** [osmItalia/italyobf#1]
Ciao,
ho lanciato ./batch.sh per la Slovenia usando poca memoria (min 100 max 800Mb), ma nel log mi pare che il problema sia un castella non creata...

[...]
Time finished: Fri Nov 18 19:44:09 CET 2016
Total time taken: 25950s
Creating OBF maps
./batch.sh: line 49: cd: OsmAndMapCreator-main: No such file or directory
Error: Could not find or load main class net.osmand.data.index.IndexBatchCreator
Maps union
Error: Could not find or load main class net.osmand.MainUtilities

**Comment by lucadelu** [comment]
Sembra che non ci sia OsmAndMapCreator..
Hai prima lanciato install.sh? Serve per installare i programmi utili per far funzionare correttamente gli altri script

**Comment by cascafico** [comment]
Si, ho lanciato install.sh
Non ho usato root, ma suppongo non scriva nulla al di fuori della home

Lunedì riprovo con calma. Ciao e...Grazie
Il 19/nov/2016 09:19, "Luca Delucchi" notifications@github.com ha scritto:
